server:
  port: 5051
  
spring:
  application:
    name: Supermercato

  datasource:
    initialization-mode: always
    password: 123456
    platform: postgres
    url: jdbc:postgresql://localhost:5433/Supermercato
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
    show-sql: true
